FROM node:16-alpine as build-step
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./my-cards-react ./
RUN npm install
RUN npm run build

FROM python:3.9
WORKDIR /app
COPY --from=build-step /app/build ./build

RUN mkdir ./backend
COPY ./backend ./backend
RUN pip install -r ./backend/requirements.txt
EXPOSE 3306

EXPOSE 3000
WORKDIR /app/backend
CMD ["gunicorn", "-b", ":3000", "app:app"]